const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.NinePatch,
		C3.Behaviors.Anchor,
		C3.Behaviors.MoveTo,
		C3.Plugins.Sprite,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.destroy,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.NoSave,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Plugins.Browser,
		C3.Behaviors.Bullet,
		C3.Plugins.Arr,
		C3.Plugins.XML,
		C3.Plugins.AJAX,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Dictionary,
		C3.Behaviors.Rotate,
		C3.Plugins.AdvancedRandom,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.BinaryData,
		C3.Behaviors.TileMovement,
		C3.Plugins.Timeline,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Json,
		C3.Plugins.TextBox,
		C3.Behaviors.Flash,
		C3.Plugins.Avix_PokiSDK_ForC3,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Acts.Clear,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.NinePatch.Cnds.CompareOpacity,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.LOS.Exps.HitDistance,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.LOS.Exps.HitUID,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Tilemap.Acts.SetTile,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.DrawingCanvas.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.Tilemap.Exps.TileAt,
		C3.Plugins.Tilemap.Acts.EraseTile,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Plugins.DrawingCanvas.Cnds.IsBetweenAngles,
		C3.Plugins.DrawingCanvas.Exps.Angle,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Behaviors.Bullet.Acts.SetBounceOffSolids,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Sin.Exps.Period,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.DrawingCanvas.Acts.Destroy,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Touch.Exps.XForID,
		C3.Plugins.Touch.Exps.YForID,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.XML.Exps.StringValue,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.XML.Acts.Load,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Dictionary.Cnds.IsEmpty,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.OnSaveComplete,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.ScrollY,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.Spritefont2.Exps.Opacity,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Spritefont2.Exps.TextHeight,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStart,
		C3.JavaScriptInEvents._include_Event238_Act6,
		C3.JavaScriptInEvents._include_Event240_Act6,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStop,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestCommercialBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnCommercialBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestRewardedBreak,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnRewardedBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.LastAdRewardSuccess,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Behaviors.TileMovement.Acts.SetGridPosition,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Dictionary.Acts.DeleteKey,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Tilemap.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Tilemap.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.NinePatch.Cnds.CompareX,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Arr.Cnds.CompareInstanceVar,
		C3.Plugins.Tilemap.Exps.TilesJSON,
		C3.Plugins.Sprite.Exps.AsJSON,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Tilemap.Acts.LoadFromJSON,
		C3.Plugins.Tilemap.Exps.Width,
		C3.Plugins.Tilemap.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.TileMovement.Acts.SetSpeed,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.Tilemap.Cnds.IsOnLayer,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.Sprite.Acts.LoadFromJsonString,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.JavaScriptInEvents._include_Event804_Act1,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Exps.Density,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.Platform.Exps.MaxFallSpeed,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Particles.Cnds.PickDistance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.AdvancedRandom.Acts.SetSeed,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Particles.Cnds.IsSpraying,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.NinePatch.Cnds.IsOnLayer,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.DrawingCanvas.Cnds.CompareInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.JavaScriptInEvents._game_Event1952_Act1,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Behaviors.TileMovement.Exps.SpeedX,
		C3.Behaviors.TileMovement.Exps.SpeedY,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Behaviors.solid.Acts.SetTags,
		C3.JavaScriptInEvents._game_Event2158_Act1,
		C3.Plugins.AdvancedRandom.Exps.Classic2d,
		C3.Plugins.AdvancedRandom.Exps.Voronoi2d,
		C3.Plugins.AdvancedRandom.Exps.Cellular2d,
		C3.Plugins.AdvancedRandom.Exps.Ridged2d,
		C3.Plugins.AdvancedRandom.Exps.Billow2d,
		C3.Plugins.Arr.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Tilemap.Exps.LayerName,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Plugins.Tilemap.Cnds.CompareInstanceVar,
		C3.Plugins.Tilemap.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Exps.replace,
		C3.JavaScriptInEvents._game_Event3597_Act1,
		C3.JavaScriptInEvents._game_Event3598_Act1,
		C3.JavaScriptInEvents._game_Event3745_Act1,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Behaviors.Tween.Acts.PauseTweens,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyLoadingFinished,
		C3.JavaScriptInEvents._loader_Event16,
		C3.Plugins.AdvancedRandom.Acts.SetOctaves,
		C3.Plugins.AdvancedRandom.Exps.RandomSeed,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Exps.Front,
		C3.Plugins.Json.Acts.PopValue,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.Platform.Exps.MaxSpeed
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Keyboard: 0},
	{type: 0},
	{skript: 0},
	{Anchor: 0},
	{MoveTo: 0},
	{notTouchZone: 0},
	{palette: 0},
	{canvasForText: 0},
	{notTouchZoneForPC: 0},
	{func: 0},
	{startTranslate: 0},
	{ID: 0},
	{noCanvas: 0},
	{comicSansText: 0},
	{TroikaText: 0},
	{whitePixelText: 0},
	{inHand: 0},
	{readyTake: 0},
	{countNumber: 0},
	{destroy: 0},
	{Physics: 0},
	{Tween: 0},
	{Timer: 0},
	{DestroyOutsideLayout: 0},
	{itemDrop: 0},
	{slotID: 0},
	{moving: 0},
	{startMovingLayout: 0},
	{Sine: 0},
	{itemInventory: 0},
	{craftAvailable: 0},
	{recipe: 0},
	{recipeCount: 0},
	{ItemCraft: 0},
	{ItemCraft2: 0},
	{TouchID: 0},
	{start_size: 0},
	{sound: 0},
	{id: 0},
	{hide: 0},
	{startW: 0},
	{startH: 0},
	{typeDop: 0},
	{typeParam: 0},
	{active: 0},
	{animation: 0},
	{btn: 0},
	{Touch: 0},
	{Solid: 0},
	{NoSave: 0},
	{tilemapMain: 0},
	{maxSpeed: 0},
	{maxRange: 0},
	{damageFall: 0},
	{speedWater: 0},
	{luckyDrop: 0},
	{luckyFood: 0},
	{luckyItem: 0},
	{car: 0},
	{AutoMelt: 0},
	{creative: 0},
	{cheatLight: 0},
	{sleep: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{LineOfSight: 0},
	{playerCollision: 0},
	{armorDone: 0},
	{menyID: 0},
	{noob_body: 0},
	{noob_part: 0},
	{noob_head: 0},
	{joyUnder: 0},
	{touchID: 0},
	{dist: 0},
	{ang: 0},
	{hisDist: 0},
	{joyStick: 0},
	{Browser: 0},
	{rayCastPos: 0},
	{destroyLine: 0},
	{canvasDestroyBlock: 0},
	{idDestroy: 0},
	{durability: 0},
	{selfUID: 0},
	{selfPos: 0},
	{typeLayer: 0},
	{doneDestroy: 0},
	{typeBlock: 0},
	{destroyBlock: 0},
	{Bullet: 0},
	{canvasParticleDestroy: 0},
	{invetroryUI: 0},
	{idSelect: 0},
	{slotSelect: 0},
	{inventory: 0},
	{XMLlanguage: 0},
	{AJAX: 0},
	{"9pUI": 0},
	{"9pCell": 0},
	{blockSettings: 0},
	{maxDur: 0},
	{destroyState: 0},
	{tbUsedWafer: 0},
	{tbUsed: 0},
	{healtUI: 0},
	{particlesRun: 0},
	{currentID: 0},
	{canvasActiveBtn: 0},
	{eatPart: 0},
	{PlatformInfo: 0},
	{totalNPC: 0},
	{npc: 0},
	{tilemapBlack: 0},
	{cache1: 0},
	{cache2: 0},
	{cache3: 0},
	{frame: 0},
	{icon: 0},
	{energy: 0},
	{processID: 0},
	{processType: 0},
	{debtDone: 0},
	{tellCollision: 0},
	{tilemapSecond: 0},
	{allItem: 0},
	{partCoin: 0},
	{ownerID: 0},
	{light: 0},
	{worldLight: 0},
	{Rotate: 0},
	{bottleEffect: 0},
	{particlesFire: 0},
	{AdvancedRandom: 0},
	{cheat: 0},
	{Pin: 0},
	{lightPlayer: 0},
	{jailStone: 0},
	{dontDestroyBlock: 0},
	{checkWhere: 0},
	{justLine: 0},
	{moveLine: 0},
	{canvasWord: 0},
	{errorSet: 0},
	{idOwner: 0},
	{curItem: 0},
	{pos: 0},
	{interactArray: 0},
	{interactSelectBlock: 0},
	{SineUo: 0},
	{SineRo: 0},
	{tnt: 0},
	{smokeParticles: 0},
	{smokeBoomParticles: 0},
	{explosion: 0},
	{enemySolid: 0},
	{"9pWaferInvetoryText": 0},
	{dictionaryGame: 0},
	{parentID: 0},
	{lightSystem: 0},
	{tutorialNPC: 0},
	{"9pMessage": 0},
	{destroySecondLayer: 0},
	{SolidObjV2: 0},
	{tbBlack: 0},
	{Mouse: 0},
	{tbMount: 0},
	{tbFade: 0},
	{cloud: 0},
	{saveGame: 0},
	{logoMenuBlock: 0},
	{tbLogo: 0},
	{justSolid: 0},
	{LocalStorage: 0},
	{dead_particles: 0},
	{generatorPart: 0},
	{dustCut1: 0},
	{V: 0},
	{G: 0},
	{mainCamera: 0},
	{who: 0},
	{touchHelper: 0},
	{inventorySelectWindow: 0},
	{craftBtn: 0},
	{curRecipeCheck: 0},
	{parentDestroy: 0},
	{getReadyToDestroy: 0},
	{door: 0},
	{something: 0},
	{blackSpriteSecondLayer: 0},
	{secondBlockSelector: 0},
	{secondCursor: 0},
	{tilemapDecor: 0},
	{waterTilemap: 0},
	{сurChunk: 0},
	{lavaTilemap: 0},
	{physicBlock: 0},
	{mobsPart: 0},
	{hp: 0},
	{hpMax: 0},
	{state: 0},
	{moveSide: 0},
	{control: 0},
	{repro: 0},
	{outSideTimer: 0},
	{herobrine_pursuit: 0},
	{moveLock: 0},
	{DestroyOnTime: 0},
	{DestroyOnTimeStart: 0},
	{mobsCollision: 0},
	{smoke2: 0},
	{BinaryData: 0},
	{newSaveSystemMain: 0},
	{lovePart: 0},
	{skyGrad: 0},
	{sun: 0},
	{star: 0},
	{herobrineFire: 0},
	{UID_: 0},
	{fire: 0},
	{sleepPart: 0},
	{helpingTutorial: 0},
	{iconForShop: 0},
	{logoMenuAny: 0},
	{expBar: 0},
	{expBarFill: 0},
	{expPoint: 0},
	{unlockSlotWithAds: 0},
	{noobInventory: 0},
	{costItemAll: 0},
	{typeZ: 0},
	{rZ: 0},
	{gZ: 0},
	{bZ: 0},
	{tilemapBack: 0},
	{whiteFlat: 0},
	{armorInventory: 0},
	{randomDamageArmor: 0},
	{Map: 0},
	{expTradeTile: 0},
	{expTradeFiller: 0},
	{tradeArrayV2: 0},
	{lockTrade: 0},
	{onOff: 0},
	{decorAnimated: 0},
	{uidChest: 0},
	{fuel: 0},
	{maxFuel: 0},
	{levelDrill: 0},
	{levelTank: 0},
	{levelSpeed: 0},
	{TileMovement: 0},
	{upgradeBTN: 0},
	{perks: 0},
	{TiledBackground: 0},
	{TimelineController: 0},
	{uidPin: 0},
	{hpMobsBar: 0},
	{hpMobsFiller: 0},
	{selfDistance: 0},
	{bowBot: 0},
	{enemyArrow: 0},
	{bowline: 0},
	{arrowKind: 0},
	{arrowDust: 0},
	{clampUpY: 0},
	{clampDownY: 0},
	{startPosY: 0},
	{DragDrop: 0},
	{slider: 0},
	{multiple: 0},
	{startY: 0},
	{reverseY: 0},
	{sliderTech: 0},
	{atopFiller: 0},
	{jetpack: 0},
	{jetSmoke: 0},
	{carCollision: 0},
	{ui: 0},
	{carParts: 0},
	{carSmokeBack: 0},
	{fuelFiller: 0},
	{magma: 0},
	{magmaPart: 0},
	{test: 0},
	{donate: 0},
	{logoLeader: 0},
	{ArrayLeaderboard: 0},
	{forCut: 0},
	{SineMain: 0},
	{SineSame: 0},
	{tapTutorial: 0},
	{iskrPart: 0},
	{JSON: 0},
	{newSaveSystem0: 0},
	{borderSolid: 0},
	{lightRed: 0},
	{particlesFireRed: 0},
	{backFNTree: 0},
	{backFN1: 0},
	{backFN2: 0},
	{backFN3: 0},
	{timer: 0},
	{newSaveSystem1: 0},
	{newSaveSystem2: 0},
	{"9patch": 0},
	{TextInput: 0},
	{Dictionary2: 0},
	{CryParticles: 0},
	{questsBord: 0},
	{idQuest: 0},
	{questsElementUi: 0},
	{DictionaryQuestsSave: 0},
	{ArrayQuests: 0},
	{w: 0},
	{reputationBar: 0},
	{reputationBarFill: 0},
	{GameMachineFrame: 0},
	{butonGameMachine: 0},
	{targetX: 0},
	{targetY: 0},
	{zSort: 0},
	{typeSort: 0},
	{VectorX: 0},
	{VectorY: 0},
	{RotationSpeed: 0},
	{startPosX: 0},
	{targetPosX: 0},
	{targetPosy: 0},
	{GameMachineObjects: 0},
	{Flash: 0},
	{GameMachineCharacter: 0},
	{TiledBackground3: 0},
	{BladeSmoother: 0},
	{Blade: 0},
	{explosionUi: 0},
	{BarDebt: 0},
	{deptBarBacl: 0},
	{PokiSDK: 0},
	{arrowOr: 0},
	{adsTextIcon: 0},
	{adsIcon: 0},
	{text: 0},
	{SineAnother: 0},
	{playerPart: 0},
	{Family_BACK: 0},
	{noobMenu: 0},
	{FamilyGameAutomat: 0},
	{FamilyZSort: 0},
	{data: 0},
	{cutState: 0},
	{damage: 0},
	{howMuch: 0},
	{soundDestroy: 0},
	{normalStart: 0},
	{lang: 0},
	{screen: 0},
	{screenAdsTrade: 0},
	{screenInteract: 0},
	{tutorialState: 0},
	{autoSave: 0},
	{currentRecipe: 0},
	{currentResult: 0},
	{timeWorld: 0},
	{curDay: 0},
	{mobilePlatform: 0},
	{newGame: 0},
	{startSaving: 0},
	{killEvilMobs: 0},
	{brokeBlock: 0},
	{delayTime: 0},
	{luckyBlockChanceDrop: 0},
	{skipTutorial: 0},
	{randomQuest: 0},
	{who_: 0},
	{who2: 0},
	{close: 0},
	{ads_interstitial_done: 0},
	{loop: 0},
	{SUM: 0},
	{fixPrice: 0},
	{onlyPrice: 0},
	{multiplerPrice: 0},
	{nX: 0},
	{posX: 0},
	{posY: 0},
	{rewardNow: 0},
	{yndxState: 0},
	{yndxRewarded: 0},
	{ads: 0},
	{protectFirstStart: 0},
	{adsProtect: 0},
	{start_stop_stateMashine_POKI: 0},
	{lastUIscreen: 0},
	{on: 0},
	{loopOffer: 0},
	{stateSlider: 0},
	{rate: 0},
	{difference: 0},
	{offsetY: 0},
	{skyColorR: 0},
	{skyColorG: 0},
	{skyColorB: 0},
	{showOrHide: 0},
	{slotSave: 0},
	{mobs: 0},
	{BufferSaveAllSlots: 0},
	{noSaveWorld: 0},
	{onlyVar: 0},
	{showTarget: 0},
	{showJetpack: 0},
	{startPokiFirst: 0},
	{invReady: 0},
	{maxStack: 0},
	{invetrotyOpen: 0},
	{heroHP: 0},
	{heroHPmax: 0},
	{heroSatiety: 0},
	{coin: 0},
	{timeFurnace: 0},
	{currentUIDopen: 0},
	{targetState: 0},
	{generatorLevel: 0},
	{girlUnlock: 0},
	{blockMode: 0},
	{controlPlayer: 0},
	{adsBar: 0},
	{spawnPoint: 0},
	{InfinityBlockPos: 0},
	{currentLevelHero: 0},
	{currentExpHero: 0},
	{currentLevelHeroReputation: 0},
	{currentReputationHero: 0},
	{upgradePointReputation: 0},
	{upgradePoint: 0},
	{tradeLevel: 0},
	{tradeExp: 0},
	{canDestroy: 0},
	{whoMuch: 0},
	{idTile: 0},
	{idBlock: 0},
	{drop: 0},
	{dropSide: 0},
	{whoID: 0},
	{whoType: 0},
	{PlayerSet: 0},
	{loadGame: 0},
	{onlyForNewGame: 0},
	{mainTilemapAndSecond_get_blocks: 0},
	{touchIDmoveItem: 0},
	{tapIDmove: 0},
	{moveID: 0},
	{uidFurnace: 0},
	{onlyTech: 0},
	{colorID: 0},
	{random_x_pos: 0},
	{bottom: 0},
	{timerMoving: 0},
	{idStart: 0},
	{idEnd: 0},
	{idItemStart: 0},
	{typeStart: 0},
	{countStart: 0},
	{numberStart: 0},
	{stringStart: 0},
	{layout: 0},
	{idInteract: 0},
	{idCell: 0},
	{idItem: 0},
	{typeItem: 0},
	{layer: 0},
	{newSlot: 0},
	{divSlot: 0},
	{aniArmor: 0},
	{cacheValueForCoin: 0},
	{currentShopID: 0},
	{currentShopList: 0},
	{howMuchMoney: 0},
	{howMuchSubstract: 0},
	{btnUIDsell: 0},
	{list: 0},
	{multipler: 0},
	{lineStone: 0},
	{"1secondCheck": 0},
	{"4secondCheck": 0},
	{GoodMobsCount: 0},
	{EvilMobsCount: 0},
	{herobrineCount: 0},
	{sideNumber: 0},
	{destroyOnTimeEnemy: 0},
	{taskRoad: 0},
	{arrowRoad: 0},
	{number: 0},
	{distToTarget: 0},
	{angleToTarget: 0},
	{toX: 0},
	{toY: 0},
	{ini: 0},
	{Signed: 0},
	{playerName: 0},
	{LeaderboardName: 0},
	{Score: 0},
	{Topnumber: 0},
	{Parameter0: 0},
	{Parameter1: 0},
	{i: 0},
	{tutState: 0},
	{what: 0},
	{idSekect: 0},
	{selectTypeQuest: 0},
	{ID_: 0},
	{idQuest_: 0},
	{subtract_object_1: 0},
	{subtract_object_2: 0},
	{subtract_object_3: 0},
	{reward_money: 0},
	{reward_Reputation: 0},
	{R: 0},
	{questTypeLast: 0},
	{questLvlLast: 0},
	{quest_type: 0},
	{quest_depth: 0},
	{lvl: 0},
	{tourchTriger: 0},
	{zoombieTriger: 0},
	{count_: 0},
	{x_loop: 0},
	{param: 0},
	{tikket_GameMachine_count: 0},
	{startTap: 0},
	{speed: 0},
	{money: 0},
	{lock_GameMachine: 0},
	{sectorCount: 0},
	{prizes: 0},
	{winningSector: 0},
	{stopMove: 0},
	{mixer: 0},
	{sizeFruits: 0},
	{Last_X: 0},
	{Last_Y: 0},
	{RotatioLorR: 0},
	{vector: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed2: 0},
	{TargetY: 0},
	{wait: 0},
	{game: 0},
	{lvlDebt: 0},
	{Debt_now: 0},
	{messageLast: 0},
	{DebtMultiplier_: 0},
	{DebtMultiplier_size: 0},
	{DebtMultiplier_prise: 0},
	{Percent: 0},
	{howMach: 0},
	{reward_object: 0},
	{reward_object_ID: 0},
	{multiplerPrice_: 0},
	{object: 0},
	{object_ID: 0},
	{coinAdsOffer: 0},
	{fix_bug: 0},
	{fix_bug2: 0},
	{haveSave: 0},
	{haveSave0: 0},
	{nameWorld: 0},
	{typeCreateWorld: 0},
	{typeCreateWorldMobs: 0},
	{typeCreateWorldMob: 0},
	{noLoad: 0},
	{armore0: 0},
	{armore1: 0},
	{armore2: 0},
	{data0: 0},
	{data1: 0},
	{data2: 0},
	{loadBase: 0},
	{height: 0},
	{width: 0},
	{chunk_width: 0},
	{chunk_height: 0},
	{offsetX_: 0},
	{offsetY_: 0},
	{grid_size: 0},
	{waterX: 0},
	{waterY: 0},
	{x: 0},
	{y: 0},
	{chunkX: 0},
	{chunkY: 0},
	{dictKey: 0},
	{val: 0},
	{scale: 0},
	{x_pos: 0},
	{y_pos: 0},
	{value: 0},
	{densityScale: 0},
	{randomCoaL: 0},
	{oreType: 0},
	{CountStrangeTree: 0},
	{count: 0},
	{startX: 0},
	{countCaves: 0},
	{firstStrt: 0},
	{x_: 0},
	{y_: 0},
	{noob_pos_done: 0},
	{x___: 0},
	{y___: 0},
	{haveSave2: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	notTouchZone: class extends self.IWorldInstance {},
	palette: class extends self.ISpriteInstance {},
	canvasForText: class extends self.IDrawingCanvasInstance {},
	notTouchZoneForPC: class extends self.IWorldInstance {},
	comicSansText: class extends self.ISpriteFontInstance {},
	TroikaText: class extends self.ISpriteFontInstance {},
	whitePixelText: class extends self.ISpriteFontInstance {},
	itemDrop: class extends self.ISpriteInstance {},
	itemInventory: class extends self.ISpriteInstance {},
	ItemCraft: class extends self.ISpriteInstance {},
	ItemCraft2: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	tilemapMain: class extends self.ITilemapInstance {},
	playerCollision: class extends self.ISpriteInstance {},
	noob_body: class extends self.ISpriteInstance {},
	noob_part: class extends self.ISpriteInstance {},
	noob_head: class extends self.ISpriteInstance {},
	joyUnder: class extends self.ISpriteInstance {},
	joyStick: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	destroyLine: class extends self.ISpriteInstance {},
	canvasDestroyBlock: class extends self.IDrawingCanvasInstance {},
	destroyBlock: class extends self.ISpriteInstance {},
	canvasParticleDestroy: class extends self.IDrawingCanvasInstance {},
	invetroryUI: class extends self.ISpriteInstance {},
	slotSelect: class extends self.ISpriteInstance {},
	inventory: class extends self.IArrayInstance {},
	XMLlanguage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	_9pUI: class extends self.IWorldInstance {},
	_9pCell: class extends self.IWorldInstance {},
	blockSettings: class extends self.IArrayInstance {},
	destroyState: class extends self.ISpriteInstance {},
	tbUsedWafer: class extends self.ITiledBackgroundInstance {},
	tbUsed: class extends self.ITiledBackgroundInstance {},
	healtUI: class extends self.ISpriteInstance {},
	particlesRun: class extends self.IParticlesInstance {},
	canvasActiveBtn: class extends self.IDrawingCanvasInstance {},
	eatPart: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	npc: class extends self.ISpriteInstance {},
	tilemapBlack: class extends self.ITilemapInstance {},
	icon: class extends self.ISpriteInstance {},
	tellCollision: class extends self.IWorldInstance {},
	tilemapSecond: class extends self.ITilemapInstance {},
	allItem: class extends self.IDictionaryInstance {},
	partCoin: class extends self.IParticlesInstance {},
	light: class extends self.ISpriteInstance {},
	worldLight: class extends self.ISpriteInstance {},
	bottleEffect: class extends self.ISpriteInstance {},
	particlesFire: class extends self.IParticlesInstance {},
	AdvancedRandom: class extends self.IInstance {},
	lightPlayer: class extends self.ISpriteInstance {},
	jailStone: class extends self.ITiledBackgroundInstance {},
	dontDestroyBlock: class extends self.IWorldInstance {},
	checkWhere: class extends self.ISpriteInstance {},
	justLine: class extends self.ITiledBackgroundInstance {},
	moveLine: class extends self.ISpriteInstance {},
	canvasWord: class extends self.IDrawingCanvasInstance {},
	errorSet: class extends self.ISpriteInstance {},
	interactArray: class extends self.IArrayInstance {},
	interactSelectBlock: class extends self.ISpriteInstance {},
	tnt: class extends self.ISpriteInstance {},
	smokeParticles: class extends self.IParticlesInstance {},
	smokeBoomParticles: class extends self.IParticlesInstance {},
	explosion: class extends self.ISpriteInstance {},
	enemySolid: class extends self.ISpriteInstance {},
	_9pWaferInvetoryText: class extends self.IWorldInstance {},
	dictionaryGame: class extends self.IDictionaryInstance {},
	lightSystem: class extends self.ISpriteInstance {},
	tutorialNPC: class extends self.ISpriteInstance {},
	_9pMessage: class extends self.IWorldInstance {},
	SolidObjV2: class extends self.ISpriteInstance {},
	tbBlack: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	tbMount: class extends self.ITiledBackgroundInstance {},
	tbFade: class extends self.ITiledBackgroundInstance {},
	cloud: class extends self.ISpriteInstance {},
	saveGame: class extends self.IDictionaryInstance {},
	logoMenuBlock: class extends self.ISpriteInstance {},
	tbLogo: class extends self.ITiledBackgroundInstance {},
	justSolid: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	dead_particles: class extends self.IParticlesInstance {},
	generatorPart: class extends self.ISpriteInstance {},
	dustCut1: class extends self.ISpriteInstance {},
	mainCamera: class extends self.ISpriteInstance {},
	touchHelper: class extends self.ISpriteInstance {},
	inventorySelectWindow: class extends self.ISpriteInstance {},
	craftBtn: class extends self.ISpriteInstance {},
	curRecipeCheck: class extends self.IDictionaryInstance {},
	door: class extends self.ISpriteInstance {},
	something: class extends self.ISpriteInstance {},
	blackSpriteSecondLayer: class extends self.ISpriteInstance {},
	secondBlockSelector: class extends self.ISpriteInstance {},
	secondCursor: class extends self.ISpriteInstance {},
	tilemapDecor: class extends self.ITilemapInstance {},
	waterTilemap: class extends self.ITilemapInstance {},
	сurChunk: class extends self.IArrayInstance {},
	lavaTilemap: class extends self.ITilemapInstance {},
	physicBlock: class extends self.ISpriteInstance {},
	mobsPart: class extends self.ISpriteInstance {},
	mobsCollision: class extends self.ISpriteInstance {},
	smoke2: class extends self.IParticlesInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	newSaveSystemMain: class extends self.IDictionaryInstance {},
	lovePart: class extends self.IParticlesInstance {},
	skyGrad: class extends self.ISpriteInstance {},
	sun: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	sleepPart: class extends self.IParticlesInstance {},
	helpingTutorial: class extends self.ISpriteInstance {},
	iconForShop: class extends self.ISpriteInstance {},
	logoMenuAny: class extends self.ISpriteInstance {},
	expBar: class extends self.ISpriteInstance {},
	expBarFill: class extends self.ITiledBackgroundInstance {},
	expPoint: class extends self.ISpriteInstance {},
	unlockSlotWithAds: class extends self.ISpriteInstance {},
	noobInventory: class extends self.ISpriteInstance {},
	costItemAll: class extends self.IArrayInstance {},
	tilemapBack: class extends self.ITilemapInstance {},
	whiteFlat: class extends self.ISpriteInstance {},
	armorInventory: class extends self.IArrayInstance {},
	randomDamageArmor: class extends self.IArrayInstance {},
	Map: class extends self.ISpriteInstance {},
	expTradeTile: class extends self.ITiledBackgroundInstance {},
	expTradeFiller: class extends self.ITiledBackgroundInstance {},
	tradeArrayV2: class extends self.IArrayInstance {},
	lockTrade: class extends self.ISpriteInstance {},
	decorAnimated: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	upgradeBTN: class extends self.ISpriteInstance {},
	perks: class extends self.IArrayInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TimelineController: class extends self.IInstance {},
	hpMobsBar: class extends self.ITiledBackgroundInstance {},
	hpMobsFiller: class extends self.ITiledBackgroundInstance {},
	bowBot: class extends self.ISpriteInstance {},
	enemyArrow: class extends self.ISpriteInstance {},
	bowline: class extends self.ISpriteInstance {},
	arrowKind: class extends self.ISpriteInstance {},
	arrowDust: class extends self.IParticlesInstance {},
	slider: class extends self.ISpriteInstance {},
	sliderTech: class extends self.ISpriteInstance {},
	atopFiller: class extends self.ITiledBackgroundInstance {},
	jetpack: class extends self.ISpriteInstance {},
	jetSmoke: class extends self.IParticlesInstance {},
	carCollision: class extends self.ISpriteInstance {},
	carParts: class extends self.ISpriteInstance {},
	carSmokeBack: class extends self.IParticlesInstance {},
	fuelFiller: class extends self.ISpriteInstance {},
	fuel: class extends self.ITiledBackgroundInstance {},
	magma: class extends self.ISpriteInstance {},
	magmaPart: class extends self.IParticlesInstance {},
	test: class extends self.IDictionaryInstance {},
	donate: class extends self.IDictionaryInstance {},
	logoLeader: class extends self.ISpriteInstance {},
	ArrayLeaderboard: class extends self.IArrayInstance {},
	forCut: class extends self.ISpriteInstance {},
	tapTutorial: class extends self.ISpriteInstance {},
	iskrPart: class extends self.IParticlesInstance {},
	JSON: class extends self.IJSONInstance {},
	newSaveSystem0: class extends self.IDictionaryInstance {},
	borderSolid: class extends self.ITiledBackgroundInstance {},
	lightRed: class extends self.ISpriteInstance {},
	particlesFireRed: class extends self.IParticlesInstance {},
	backFNTree: class extends self.ISpriteInstance {},
	backFN1: class extends self.ITiledBackgroundInstance {},
	backFN2: class extends self.ITiledBackgroundInstance {},
	backFN3: class extends self.ITiledBackgroundInstance {},
	timer: class extends self.ISpriteInstance {},
	newSaveSystem1: class extends self.IDictionaryInstance {},
	newSaveSystem2: class extends self.IDictionaryInstance {},
	_9patch: class extends self.IWorldInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Dictionary2: class extends self.IDictionaryInstance {},
	CryParticles: class extends self.IParticlesInstance {},
	questsBord: class extends self.ISpriteInstance {},
	questsElementUi: class extends self.ISpriteInstance {},
	DictionaryQuestsSave: class extends self.IDictionaryInstance {},
	ArrayQuests: class extends self.IArrayInstance {},
	reputationBar: class extends self.ISpriteInstance {},
	reputationBarFill: class extends self.ITiledBackgroundInstance {},
	GameMachineFrame: class extends self.ISpriteInstance {},
	butonGameMachine: class extends self.ISpriteInstance {},
	GameMachineObjects: class extends self.ISpriteInstance {},
	GameMachineCharacter: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	BladeSmoother: class extends self.ISpriteInstance {},
	Blade: class extends self.ISpriteInstance {},
	explosionUi: class extends self.ISpriteInstance {},
	BarDebt: class extends self.ITiledBackgroundInstance {},
	deptBarBacl: class extends self.IWorldInstance {},
	PokiSDK: class extends self.IInstance {},
	arrowOr: class extends self.ISpriteInstance {},
	adsTextIcon: class extends self.ITextInstance {},
	adsIcon: class extends self.ISpriteInstance {},
	text: class extends self.ISpriteFontInstance {},
	playerPart: class extends self.ISpriteInstance {},
	Family_BACK: class extends self.ITiledBackgroundInstance {},
	noobMenu: class extends self.ISpriteInstance {},
	FamilyGameAutomat: class extends self.ISpriteInstance {},
	FamilyZSort: class extends self.ISpriteInstance {}
}