const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Avix_PokiSDK_ForC3,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Share,
		C3.Plugins.BinaryData,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.FileSystem,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Json,
		C3.Plugins.NinePatch,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Plugins.Gritsenko_Spine,
		C3.Plugins.Particles,
		C3.Plugins.TextBox,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Json.Exps.UID,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.NinePatch.Acts.MoveToTop,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Gritsenko_Spine.Exps.UID,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.NinePatch.Exps.Count,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.NinePatch.Exps.ColorValue,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.NinePatch.Acts.MoveToBottom,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layertolayerx,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Cnds.PickParent,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Gritsenko_Spine.Exps.X,
		C3.Plugins.Gritsenko_Spine.Exps.Width,
		C3.Plugins.System.Exps.layertolayery,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.NinePatch.Cnds.HasParent,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.NinePatch.Cnds.IsOnScreen,
		C3.Plugins.Gritsenko_Spine.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Exps.WheelDeltaY,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Share.Cnds.IsSharingFilesSupported,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.NinePatch.Exps.Angle,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Gritsenko_Spine.Cnds.IsVisible,
		C3.Plugins.Gritsenko_Spine.Acts.SetVisible,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.Share.Acts.AddFile,
		C3.Plugins.Share.Acts.Share,
		C3.ScriptsInEvents.Evsnapshotshare_Event44_Act1,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceHeight,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Acts.ScrollY,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Gritsenko_Spine.Acts.MoveToBottom,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Gritsenko_Spine.Acts.SetAnimationMix,
		C3.Plugins.Gritsenko_Spine.Exps.CurrentAnimation,
		C3.Plugins.Gritsenko_Spine.Acts.SetAnimation,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Gritsenko_Spine.Acts.SetInstanceVar,
		C3.Plugins.Gritsenko_Spine.Cnds.PickParent,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.JoinString,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.Gritsenko_Spine.Acts.SetX,
		C3.Plugins.Gritsenko_Spine.Acts.SetY,
		C3.Plugins.Gritsenko_Spine.Exps.Height,
		C3.Plugins.Gritsenko_Spine.Acts.CreateCustomSkin,
		C3.Plugins.Gritsenko_Spine.Acts.AddCustomSkin,
		C3.Plugins.Gritsenko_Spine.Acts.SetCustomSkin,
		C3.Plugins.Gritsenko_Spine.Acts.SetSlotColor,
		C3.Plugins.Gritsenko_Spine.Acts.ApplySlotColors,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Gritsenko_Spine.Cnds.CompareInstanceVar,
		C3.Plugins.Gritsenko_Spine.Exps.Count,
		C3.Plugins.Gritsenko_Spine.Exps.LayerName,
		C3.Plugins.Gritsenko_Spine.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.ImageHeight,
		C3.Plugins.TiledBg.Acts.SetImageScaleX,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStart,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStop,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestCommercialBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.CommercialBreakPossible,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnCommercialBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestRewardedBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnRewardedBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.LastAdRewardSuccess,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Particles.Acts.SetAngleRandomiser,
		C3.Plugins.Particles.Acts.SetX,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.AJAX.Cnds.OnProgress,
		C3.Plugins.AJAX.Exps.Progress,
		C3.Plugins.AJAX.Cnds.OnAnyError,
		C3.Plugins.Json.Cnds.PickByUID,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Gritsenko_Spine.Cnds.OnCreated,
		C3.Plugins.Gritsenko_Spine.Acts.AddChild,
		C3.Plugins.Gritsenko_Spine.Acts.SetEffectEnabled,
		C3.Plugins.Gritsenko_Spine.Acts.LoadSpineFiles,
		C3.Plugins.Gritsenko_Spine.Cnds.OnSkeletonLoaded,
		C3.Plugins.Gritsenko_Spine.Acts.SetSkin,
		C3.Plugins.Gritsenko_Spine.Exps.IID,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Gritsenko_Spine.Cnds.PickChildren,
		C3.Plugins.Gritsenko_Spine.Acts.SetSize,
		C3.Plugins.Gritsenko_Spine.Exps.SkeletonScale,
		C3.Plugins.Gritsenko_Spine.Acts.SetOpacity,
		C3.Plugins.Gritsenko_Spine.Exps.CurrentSkin,
		C3.Plugins.Gritsenko_Spine.Acts.SetAngle
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Touch: 0},
	{AJAX: 0},
	{PokiSDK: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{Share: 0},
	{BinaryData: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{FileSystem: 0},
	{auxColorArray: 0},
	{Mouse: 0},
	{txtDebug: 0},
	{txtTest: 0},
	{wallBg: 0},
	{txtStep: 0},
	{jsonPartsRoom: 0},
	{jsonPartsChar: 0},
	{jsonStateRoom: 0},
	{jsonStateChar: 0},
	{jsonAuxChar: 0},
	{jsonSaveData: 0},
	{jsonSaveUnlocks: 0},
	{jsonAuxCharPresets: 0},
	{jsonBaseSaveData: 0},
	{isCharacter: 0},
	{marginHor: 0},
	{marginVert: 0},
	{buttonsPerLine: 0},
	{categoriesCSV: 0},
	{minScrollHor: 0},
	{maxScrollHor: 0},
	{minScrollVert: 0},
	{maxScrollVert: 0},
	{scrollPointItem: 0},
	{scrollPointCategories: 0},
	{scrollPointColors: 0},
	{currentScrollY: 0},
	{currentScrollX: 0},
	{currentScrollColors: 0},
	{lastScrollX: 0},
	{lastScrollY: 0},
	{lastScrollColors: 0},
	{minScrollColor: 0},
	{maxScrollColor: 0},
	{lastVisibleState: 0},
	{bgInventory: 0},
	{partID: 0},
	{categoryID: 0},
	{baseY: 0},
	{containerUID: 0},
	{premium: 0},
	{baseScale: 0},
	{animationTrigger: 0},
	{baseColor: 0},
	{btnPart: 0},
	{category_tags: 0},
	{baseX: 0},
	{btnCategory: 0},
	{parentMenuUID: 0},
	{bgCategories: 0},
	{colorsList: 0},
	{bgColors: 0},
	{colorData: 0},
	{btnColor: 0},
	{tmbCharPart: 0},
	{tmbCharCategory: 0},
	{btnColor_extras: 0},
	{uiScroll: 0},
	{tmbRoomPart: 0},
	{colorIndex: 0},
	{btnPartColor: 0},
	{roomPartParentUID: 0},
	{maxScroll: 0},
	{minScroll: 0},
	{currentScroll: 0},
	{lastScroll: 0},
	{scrollPoint: 0},
	{currentColorIndex: 0},
	{bgPartColors: 0},
	{btnColorCategories: 0},
	{dragPart: 0},
	{pose: 0},
	{spineUID: 0},
	{btnPose: 0},
	{Tween: 0},
	{bgPoses: 0},
	{btnEditChar: 0},
	{bgConfigMenu: 0},
	{tmbRoomCategory: 0},
	{btnEditHouse: 0},
	{btnBack: 0},
	{saveID: 0},
	{btnChar: 0},
	{btnClear: 0},
	{btnShowMenu: 0},
	{btnRandom: 0},
	{isOpen: 0},
	{btnCharList: 0},
	{linkedUID: 0},
	{btnDelete: 0},
	{auxScanID: 0},
	{locked: 0},
	{DragDrop: 0},
	{btnCharSpine: 0},
	{btnSnapshotCancel: 0},
	{btnShare: 0},
	{btnDownload: 0},
	{btnSnapshot: 0},
	{btnRotate: 0},
	{nextLayout: 0},
	{sprTransition: 0},
	{lastSkin: 0},
	{lastColor: 0},
	{btnUndo: 0},
	{btnConfig: 0},
	{btnConfigCancel: 0},
	{btnSound: 0},
	{Sine: 0},
	{sprDeviceRotate: 0},
	{Rotate: 0},
	{Timer: 0},
	{sprLoading: 0},
	{bgFlat: 0},
	{bgSnapshot: 0},
	{sprSnapshot: 0},
	{uiAD: 0},
	{bgOrientation: 0},
	{uiNew: 0},
	{scanID: 0},
	{isWalled: 0},
	{edgeOffset: 0},
	{partTags: 0},
	{skipScan: 0},
	{attachedToUID: 0},
	{Zort: 0},
	{isItem: 0},
	{selfZ: 0},
	{partChar: 0},
	{partCarpet01: 0},
	{partCarpet02: 0},
	{partCarpet03: 0},
	{partCarpet04: 0},
	{partCouch01: 0},
	{partBed01: 0},
	{partCouch02: 0},
	{partCouch03: 0},
	{partTable01: 0},
	{partTable02: 0},
	{partTable03: 0},
	{partTable04: 0},
	{partFloorLamp01: 0},
	{partShelf01: 0},
	{partBed02: 0},
	{partPlant01: 0},
	{partCatFood01: 0},
	{partCouch04: 0},
	{partItemToy02: 0},
	{partTable07: 0},
	{partTable05: 0},
	{partTable06: 0},
	{partTable08: 0},
	{partItemToy01: 0},
	{partItemPresent01: 0},
	{partItemPresent02: 0},
	{partChair01: 0},
	{partChair02: 0},
	{partItemDollHouse01: 0},
	{partChimney01: 0},
	{partBed03: 0},
	{partXmasTree01: 0},
	{partAirShelf01: 0},
	{partWindowPlain01: 0},
	{partWindowCurtain01: 0},
	{partWindowPlain02: 0},
	{partWindowPlain03: 0},
	{partPainting01: 0},
	{partPainting02: 0},
	{partPainting03: 0},
	{partClock01: 0},
	{partWindowRollup01: 0},
	{partWindowCurtain02: 0},
	{partWindowRollup02: 0},
	{partWindowCurtain03: 0},
	{partWindowRollup03: 0},
	{partWalledTV01: 0},
	{partPainting04: 0},
	{partPainting05: 0},
	{partPainting06: 0},
	{partPainting07: 0},
	{partPainting08: 0},
	{partAirShelf02: 0},
	{partDecoXmas01: 0},
	{partHangingLamp01: 0},
	{partHangingPlant01: 0},
	{partItemLamp01: 0},
	{partItemLamp02: 0},
	{partCat01: 0},
	{partCat02: 0},
	{partCat03: 0},
	{partCat04: 0},
	{partItemTV01: 0},
	{partItemLaptop01: 0},
	{partItemTablet01: 0},
	{partItemCandle01: 0},
	{partPlant02: 0},
	{partPlant03: 0},
	{partPlant04: 0},
	{auxFloorline: 0},
	{colCamBorder: 0},
	{lastDragUID: 0},
	{lastFocusedUID: 0},
	{ScrollTo: 0},
	{auxCam: 0},
	{horizontal: 0},
	{vertical: 0},
	{auxRoomCollider_Floor: 0},
	{bothWays: 0},
	{auxRoomCollider_Wall: 0},
	{defaultFiles: 0},
	{skinData: 0},
	{animation: 0},
	{auxSkinData: 0},
	{spnChar: 0},
	{btnHouse: 0},
	{btnUID: 0},
	{curPart: 0},
	{curColor: 0},
	{sprRoomFrame: 0},
	{bgBasic: 0},
	{sprPointer: 0},
	{uiItemShadow: 0},
	{index: 0},
	{sprRoomWallLeft: 0},
	{sprRoomWallRight: 0},
	{sprRoomFloorL: 0},
	{sprRoomFloorR: 0},
	{sprRoomExtraSplit: 0},
	{bgRoomFloorExtraL: 0},
	{bgRoomFloorExtraL2: 0},
	{prtBigStar: 0},
	{prtSmallStar: 0},
	{bgCharList: 0},
	{sprLogo: 0},
	{uiSubcolor: 0},
	{txtGeneric: 0},
	{txtOUTPUT: 0},
	{bgFence: 0},
	{bgStreet: 0},
	{bgSkyline: 0},
	{category: 0},
	{btnQuickBodyPart: 0},
	{Variable1: 0},
	{bgGrass: 0},
	{bgGrassSnow: 0},
	{prtSnow: 0},
	{famJsonParts: 0},
	{famJsonStates: 0},
	{famJsonAux: 0},
	{famBtnParts: 0},
	{famBtnCategories: 0},
	{famBtnColors: 0},
	{famBtnNavigation: 0},
	{famFloortiles: 0},
	{famWallpapers: 0},
	{famBtnOthers: 0},
	{famDraggable: 0},
	{famPartParent: 0},
	{famSpine: 0},
	{famMenuContainer: 0},
	{Anchor: 0},
	{famAnchored: 0},
	{famCamBlockers: 0},
	{famThumbnails: 0},
	{famSprHideOnSnapshot: 0},
	{famPatchHideOnSnapshot: 0},
	{famPatchDragBlock: 0},
	{famSprDragBlock: 0},
	{famParticles: 0},
	{TEST_COLOR_LIST_TYPE: 0},
	{MENU_LAST_TOUCHED_ID: 0},
	{categoryDist: 0},
	{categoryYoffset: 0},
	{thumbnailRatio: 0},
	{x: 0},
	{y: 0},
	{width: 0},
	{height: 0},
	{areaWidth: 0},
	{areaHeight: 0},
	{x0: 0},
	{y0: 0},
	{totalParts: 0},
	{partList: 0},
	{distHor: 0},
	{btnMidPoint: 0},
	{jsonUID: 0},
	{thumbnailRatio_avatar: 0},
	{thumbnailRatio_room: 0},
	{chosenParts: 0},
	{colorWidth: 0},
	{menuScale: 0},
	{menuUID: 0},
	{tag: 0},
	{colorList: 0},
	{exceptionTag: 0},
	{OLDx: 0},
	{OLDy: 0},
	{btnWidth: 0},
	{borderX: 0},
	{borderY: 0},
	{colorLIst: 0},
	{needsReset: 0},
	{gapY: 0},
	{extraOffsetY: 0},
	{tabHeight: 0},
	{totalTabs: 0},
	{partUID: 0},
	{exceptionUID: 0},
	{spawnBBoxLeft: 0},
	{spawnBBoxRight: 0},
	{mainUID: 0},
	{returnNumber: 0},
	{tagToCheck: 0},
	{exceptionList: 0},
	{colorsMenuUID: 0},
	{scaleChange: 0},
	{timeSpan: 0},
	{step: 0},
	{needsMoving: 0},
	{midpoint: 0},
	{autoscrollTolerance: 0},
	{midstep: 0},
	{buttonCount: 0},
	{buttonLimit: 0},
	{localMaxScroll: 0},
	{returnCursorParts: 0},
	{clearList: 0},
	{currentColors: 0},
	{currentColorVal: 0},
	{draggableUID: 0},
	{layer: 0},
	{HEXDIGTS: 0},
	{hex: 0},
	{SAVE_DATA_FILE: 0},
	{SHARE_URL: 0},
	{offsetX: 0},
	{offsetY: 0},
	{margin: 0},
	{btnY: 0},
	{DEBUG_VAL: 0},
	{DEBUG_STRING: 0},
	{DEBUG_BOOL: 0},
	{CURRENT_ROOM_SAVE_ID: 0},
	{ROOM_EXCEPTION_TAGS: 0},
	{ROOM_DEFAULT_CATEGORY_LIST: 0},
	{ROOM_TEST_CATEGORY_LIST: 0},
	{CAM_LEFT_LIMIT: 0},
	{CAM_RIGHT_LIMIT: 0},
	{CAM_HOUSE_SCALE: 0},
	{BORDER_SPEED: 0},
	{CAM_TOP_LIMIT: 0},
	{houseScrollOffset: 0},
	{dragUID: 0},
	{deltaX: 0},
	{camX: 0},
	{closestUID: 0},
	{lastDistance: 0},
	{centerPoint: 0},
	{tolerance: 0},
	{LIMIT_RATIO: 0},
	{partIndex: 0},
	{mainLayer: 0},
	{layerList: 0},
	{partsUIDlist: 0},
	{colorOrder: 0},
	{colorsData: 0},
	{totalColorIndexes: 0},
	{defaultColorData: 0},
	{needsChecking: 0},
	{ceilingLine: 0},
	{UID: 0},
	{carpetZfix: 0},
	{parentZ: 0},
	{zort: 0},
	{assetsList: 0},
	{mainSortZ: 0},
	{menuHeight: 0},
	{menuWidth: 0},
	{part_ID: 0},
	{charX: 0},
	{charY: 0},
	{partX: 0},
	{partY: 0},
	{partWidth: 0},
	{partHeight: 0},
	{returnClearValue: 0},
	{charUID: 0},
	{roomPartUID: 0},
	{tolerancePercent: 0},
	{menuY: 0},
	{poseList: 0},
	{itemX: 0},
	{itemY: 0},
	{itemUID: 0},
	{partIDstring: 0},
	{menuShownDistance: 0},
	{menuDistance: 0},
	{menuOffset: 0},
	{borderMargin: 0},
	{menuHeightPortrait: 0},
	{categoryHeight: 0},
	{currentIndex: 0},
	{charsOnStage: 0},
	{totalChars: 0},
	{currentSaveID: 0},
	{lastX: 0},
	{roomJSON: 0},
	{currentJSONlist: 0},
	{scanIndex: 0},
	{currentPart: 0},
	{currentScanID: 0},
	{currentColorData: 0},
	{currentFlipped: 0},
	{currentAttachedTo: 0},
	{currentZindex: 0},
	{CHAR_DEFAULT_TAGS_LIST: 0},
	{CHAR_EXCEPTION_TAGS: 0},
	{CHAR_BODY_CATEGORIES: 0},
	{CURRENT_CHAR_SAVE_ID: 0},
	{scaleVar: 0},
	{currentCategory: 0},
	{currentSkin: 0},
	{skinString: 0},
	{oldSkin: 0},
	{skin: 0},
	{returnList: 0},
	{skinIndex: 0},
	{partSkin: 0},
	{currentSlot: 0},
	{slotsList: 0},
	{currentSlots: 0},
	{skinSlots: 0},
	{partsLists: 0},
	{colorsString: 0},
	{oldColor: 0},
	{color: 0},
	{randomPos: 0},
	{WEIGHTED_PARTS_LIST: 0},
	{WEIGHTED_PARTS_PROBABILITY: 0},
	{partsList: 0},
	{chosenIndex: 0},
	{auxList: 0},
	{blankSkinData: 0},
	{baseMixSpeed: 0},
	{chance: 0},
	{SKIN_BLINK_EXCEPTIONS: 0},
	{SKIN_BLINK_SKIN: 0},
	{BLINK_TIMER: 0},
	{stepDelay: 0},
	{popTime: 0},
	{waitTime: 0},
	{marginHouse: 0},
	{marginChar: 0},
	{ADS_LAST_TAG: 0},
	{POKI_firstTap: 0},
	{POKI_gameStart: 0},
	{LAST_LAYOUT: 0},
	{INPUT_ON: 0},
	{RENDERS_PORTRAIT: 0},
	{IS_PORTRAIT: 0},
	{portraitValueThreshold: 0},
	{LAYOUT_LIST: 0},
	{angleRange: 0},
	{timeout: 0},
	{JSON_CSV_LIST: 0},
	{JSON_PARSING_INDEX: 0},
	{ROOM_PARTS_FILE: 0},
	{CHAR_PARTS_FILE: 0},
	{SPINE_CHAR_FILE: 0},
	{jsonList: 0},
	{return: 0},
	{currentPartTags: 0},
	{currentTag: 0},
	{returnColors: 0},
	{returnPalIndex: 0},
	{returnColorIndexes: 0},
	{returnColorOrder: 0},
	{roomPartID: 0},
	{returnCategory: 0},
	{returnVal: 0},
	{categoryList: 0},
	{returnAnimation: 0},
	{returnValue: 0},
	{jsonData: 0},
	{type: 0},
	{slot: 0},
	{lock: 0},
	{SPINE_DEFAULT_SKIN: 0},
	{SPINE_DEFAULT_COLORS: 0},
	{RELOAD_WAIT: 0},
	{SPINE_ANIMATION_EXCEPTIONS: 0},
	{SPINE_DEFAULT_FILES: 0},
	{filenames: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	PokiSDK: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Share: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	FileSystem: class extends self.IInstance {},
	auxColorArray: class extends self.IArrayInstance {},
	Mouse: class extends self.IInstance {},
	txtDebug: class extends self.ITextInstance {},
	txtTest: class extends self.ITextInstance {},
	wallBg: class extends self.ITiledBackgroundInstance {},
	txtStep: class extends self.ITextInstance {},
	jsonPartsRoom: class extends self.IJSONInstance {},
	jsonPartsChar: class extends self.IJSONInstance {},
	jsonStateRoom: class extends self.IJSONInstance {},
	jsonStateChar: class extends self.IJSONInstance {},
	jsonAuxChar: class extends self.IJSONInstance {},
	jsonSaveData: class extends self.IJSONInstance {},
	jsonSaveUnlocks: class extends self.IJSONInstance {},
	jsonAuxCharPresets: class extends self.IJSONInstance {},
	jsonBaseSaveData: class extends self.IJSONInstance {},
	bgInventory: class extends self.IWorldInstance {},
	btnPart: class extends self.ISpriteInstance {},
	btnCategory: class extends self.ISpriteInstance {},
	bgCategories: class extends self.IWorldInstance {},
	bgColors: class extends self.IWorldInstance {},
	btnColor: class extends self.ISpriteInstance {},
	tmbCharPart: class extends self.ISpriteInstance {},
	tmbCharCategory: class extends self.ISpriteInstance {},
	btnColor_extras: class extends self.ISpriteInstance {},
	uiScroll: class extends self.IWorldInstance {},
	tmbRoomPart: class extends self.ISpriteInstance {},
	btnPartColor: class extends self.ISpriteInstance {},
	bgPartColors: class extends self.IWorldInstance {},
	btnColorCategories: class extends self.IWorldInstance {},
	dragPart: class extends self.ISpriteInstance {},
	btnPose: class extends self.ISpriteInstance {},
	bgPoses: class extends self.IWorldInstance {},
	btnEditChar: class extends self.ISpriteInstance {},
	bgConfigMenu: class extends self.IWorldInstance {},
	tmbRoomCategory: class extends self.ISpriteInstance {},
	btnEditHouse: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnChar: class extends self.ISpriteInstance {},
	btnClear: class extends self.ISpriteInstance {},
	btnShowMenu: class extends self.ISpriteInstance {},
	btnRandom: class extends self.ISpriteInstance {},
	btnCharList: class extends self.ISpriteInstance {},
	btnDelete: class extends self.ISpriteInstance {},
	btnCharSpine: class extends self.ISpriteInstance {},
	btnSnapshotCancel: class extends self.ISpriteInstance {},
	btnShare: class extends self.ISpriteInstance {},
	btnDownload: class extends self.ISpriteInstance {},
	btnSnapshot: class extends self.ISpriteInstance {},
	btnRotate: class extends self.ISpriteInstance {},
	sprTransition: class extends self.ISpriteInstance {},
	btnUndo: class extends self.ISpriteInstance {},
	btnConfig: class extends self.ISpriteInstance {},
	btnConfigCancel: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	sprDeviceRotate: class extends self.ISpriteInstance {},
	sprLoading: class extends self.ISpriteInstance {},
	bgFlat: class extends self.ITiledBackgroundInstance {},
	bgSnapshot: class extends self.IWorldInstance {},
	sprSnapshot: class extends self.ISpriteInstance {},
	uiAD: class extends self.ISpriteInstance {},
	bgOrientation: class extends self.ITiledBackgroundInstance {},
	uiNew: class extends self.ISpriteInstance {},
	partChar: class extends self.ISpriteInstance {},
	partCarpet01: class extends self.ISpriteInstance {},
	partCarpet02: class extends self.ISpriteInstance {},
	partCarpet03: class extends self.ISpriteInstance {},
	partCarpet04: class extends self.ISpriteInstance {},
	partCouch01: class extends self.ISpriteInstance {},
	partBed01: class extends self.ISpriteInstance {},
	partCouch02: class extends self.ISpriteInstance {},
	partCouch03: class extends self.ISpriteInstance {},
	partTable01: class extends self.ISpriteInstance {},
	partTable02: class extends self.ISpriteInstance {},
	partTable03: class extends self.ISpriteInstance {},
	partTable04: class extends self.ISpriteInstance {},
	partFloorLamp01: class extends self.ISpriteInstance {},
	partShelf01: class extends self.ISpriteInstance {},
	partBed02: class extends self.ISpriteInstance {},
	partPlant01: class extends self.ISpriteInstance {},
	partCatFood01: class extends self.ISpriteInstance {},
	partCouch04: class extends self.ISpriteInstance {},
	partItemToy02: class extends self.ISpriteInstance {},
	partTable07: class extends self.ISpriteInstance {},
	partTable05: class extends self.ISpriteInstance {},
	partTable06: class extends self.ISpriteInstance {},
	partTable08: class extends self.ISpriteInstance {},
	partItemToy01: class extends self.ISpriteInstance {},
	partItemPresent01: class extends self.ISpriteInstance {},
	partItemPresent02: class extends self.ISpriteInstance {},
	partChair01: class extends self.ISpriteInstance {},
	partChair02: class extends self.ISpriteInstance {},
	partItemDollHouse01: class extends self.ISpriteInstance {},
	partChimney01: class extends self.ISpriteInstance {},
	partBed03: class extends self.ISpriteInstance {},
	partXmasTree01: class extends self.ISpriteInstance {},
	partAirShelf01: class extends self.ISpriteInstance {},
	partWindowPlain01: class extends self.ISpriteInstance {},
	partWindowCurtain01: class extends self.ISpriteInstance {},
	partWindowPlain02: class extends self.ISpriteInstance {},
	partWindowPlain03: class extends self.ISpriteInstance {},
	partPainting01: class extends self.ISpriteInstance {},
	partPainting02: class extends self.ISpriteInstance {},
	partPainting03: class extends self.ISpriteInstance {},
	partClock01: class extends self.ISpriteInstance {},
	partWindowRollup01: class extends self.ISpriteInstance {},
	partWindowCurtain02: class extends self.ISpriteInstance {},
	partWindowRollup02: class extends self.ISpriteInstance {},
	partWindowCurtain03: class extends self.ISpriteInstance {},
	partWindowRollup03: class extends self.ISpriteInstance {},
	partWalledTV01: class extends self.ISpriteInstance {},
	partPainting04: class extends self.ISpriteInstance {},
	partPainting05: class extends self.ISpriteInstance {},
	partPainting06: class extends self.ISpriteInstance {},
	partPainting07: class extends self.ISpriteInstance {},
	partPainting08: class extends self.ISpriteInstance {},
	partAirShelf02: class extends self.ISpriteInstance {},
	partDecoXmas01: class extends self.ISpriteInstance {},
	partHangingLamp01: class extends self.ISpriteInstance {},
	partHangingPlant01: class extends self.ISpriteInstance {},
	partItemLamp01: class extends self.ISpriteInstance {},
	partItemLamp02: class extends self.ISpriteInstance {},
	partCat01: class extends self.ISpriteInstance {},
	partCat02: class extends self.ISpriteInstance {},
	partCat03: class extends self.ISpriteInstance {},
	partCat04: class extends self.ISpriteInstance {},
	partItemTV01: class extends self.ISpriteInstance {},
	partItemLaptop01: class extends self.ISpriteInstance {},
	partItemTablet01: class extends self.ISpriteInstance {},
	partItemCandle01: class extends self.ISpriteInstance {},
	partPlant02: class extends self.ISpriteInstance {},
	partPlant03: class extends self.ISpriteInstance {},
	partPlant04: class extends self.ISpriteInstance {},
	auxFloorline: class extends self.ITiledBackgroundInstance {},
	colCamBorder: class extends self.ISpriteInstance {},
	auxCam: class extends self.ISpriteInstance {},
	auxRoomCollider_Floor: class extends self.ITiledBackgroundInstance {},
	auxRoomCollider_Wall: class extends self.ITiledBackgroundInstance {},
	spnChar: class extends self.IWorldInstance {},
	btnHouse: class extends self.ISpriteInstance {},
	curPart: class extends self.ISpriteInstance {},
	curColor: class extends self.ISpriteInstance {},
	sprRoomFrame: class extends self.ISpriteInstance {},
	bgBasic: class extends self.ITiledBackgroundInstance {},
	sprPointer: class extends self.ISpriteInstance {},
	uiItemShadow: class extends self.ISpriteInstance {},
	sprRoomWallLeft: class extends self.ISpriteInstance {},
	sprRoomWallRight: class extends self.ISpriteInstance {},
	sprRoomFloorL: class extends self.ISpriteInstance {},
	sprRoomFloorR: class extends self.ISpriteInstance {},
	sprRoomExtraSplit: class extends self.ISpriteInstance {},
	bgRoomFloorExtraL: class extends self.ITiledBackgroundInstance {},
	bgRoomFloorExtraL2: class extends self.ITiledBackgroundInstance {},
	prtBigStar: class extends self.IParticlesInstance {},
	prtSmallStar: class extends self.IParticlesInstance {},
	bgCharList: class extends self.IWorldInstance {},
	sprLogo: class extends self.ISpriteInstance {},
	uiSubcolor: class extends self.ISpriteInstance {},
	txtGeneric: class extends self.ITextInstance {},
	txtOUTPUT: class extends self.ITextInputInstance {},
	bgFence: class extends self.ITiledBackgroundInstance {},
	bgStreet: class extends self.ITiledBackgroundInstance {},
	bgSkyline: class extends self.ITiledBackgroundInstance {},
	btnQuickBodyPart: class extends self.ISpriteInstance {},
	bgGrass: class extends self.ITiledBackgroundInstance {},
	bgGrassSnow: class extends self.ITiledBackgroundInstance {},
	prtSnow: class extends self.IParticlesInstance {},
	famJsonParts: class extends self.IJSONInstance {},
	famJsonStates: class extends self.IJSONInstance {},
	famJsonAux: class extends self.IJSONInstance {},
	famBtnParts: class extends self.ISpriteInstance {},
	famBtnCategories: class extends self.ISpriteInstance {},
	famBtnColors: class extends self.ISpriteInstance {},
	famBtnNavigation: class extends self.ISpriteInstance {},
	famFloortiles: class extends self.ISpriteInstance {},
	famWallpapers: class extends self.ISpriteInstance {},
	famBtnOthers: class extends self.ISpriteInstance {},
	famDraggable: class extends self.ISpriteInstance {},
	famPartParent: class extends self.ISpriteInstance {},
	famSpine: class extends self.IWorldInstance {},
	famMenuContainer: class extends self.IWorldInstance {},
	famAnchored: class extends self.ISpriteInstance {},
	famCamBlockers: class extends self.IWorldInstance {},
	famThumbnails: class extends self.ISpriteInstance {},
	famSprHideOnSnapshot: class extends self.ISpriteInstance {},
	famPatchHideOnSnapshot: class extends self.IWorldInstance {},
	famPatchDragBlock: class extends self.IWorldInstance {},
	famSprDragBlock: class extends self.ISpriteInstance {},
	famParticles: class extends self.IParticlesInstance {}
}